language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - yarn

script:
  - yarn run build

deploy:
    provider: surge
    project: ./build/
    domain: blynk-client.surge.sh
